name: Publish Package to PyPI
on:
  push:
    branches: [main]

permissions:
  contents: write  # allow creating/pushing tags (limited to repo contents)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full git history to include tags&#8203;:contentReference[oaicite:7]{index=7}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Bump version tag (using setuptools_scm for versioning)
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch        # default to patch version bump
          WITH_V: "true"            # prefix tag with "v" (e.g., v1.0.1)
          GIT_API_TAGGING: "false"  # use git CLI instead of API for tagging (ensures local tag presence)

      - name: Build distribution
        run: |
          pip install --upgrade build setuptools_scm
          python -m build  # creates dist/ with wheel and sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          # The PyPI API token (add this in your repo settings -> Secrets)
