name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required for pushing tags
  id-token: write  # Mandatory for PyPI Trusted Publishing

jobs:
  # 🏗 Step 1: Build the package and store it as an artifact
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full Git history with tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade build setuptools_scm

      - name: Build the package
        run: python -m build  # Generates dist/ folder

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  # 🚀 Step 2: Publish to **TestPyPI** for pre-release validation
  publish-to-testpypi:
    name: Publish to TestPyPI 🧪
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OpenID Connect authentication

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # 🎉 Step 3: If the commit is tagged, publish the package to PyPI
  publish-to-pypi:
    name: Publish to PyPI 📦
    if: startsWith(github.ref, 'refs/tags/')  # Only publish if commit is tagged
    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OpenID Connect authentication

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
